version: '3.9'

services:
  mysql-appuser-db:
    image: mysql:8.0
    container_name: container_mysql_appuser
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appuser
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin-appuser:
    container_name: phpmyadmin-appuserdb
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8087:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-appuser-db
      PMA_USER: user
      PMA_PASSWORD: user
    depends_on:
      - mysql-appuser-db
    restart: unless-stopped



volumes:
  mysql_data:
    driver: local